version: '3'

services:
  rhodes:
    build:
      context: ./rhodes
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./rhodes:/var/www
    environment:
      MANISA_URI: "http://rhodes_manisa_1:8081"
    
  manisa:
    build:
      context: ./manisa
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./manisa:/var/www
    environment:
      ACCESS_TOKEN: "rFxeUauT0DI-qhzmPvd2QOu075dcoEwSxIGoJyoQ2Fo"
      SPACE_ID: "kcgcl5c4dlw8"
      ENVIRONMENT:  "master"
     
