version: '3'

services:
  rhodes:
    build:
      context: ./rhodes
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./rhodes:/var/www
    
  manisa:
    build:
      context: ./manisa
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./manisa:/var/www
     
