      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" 
        width="140" height="120" 
        xmlns="http://www.w3.org/2000/svg" 
        role="img" aria-label="Placeholder: 140x140" 
        preserveAspectRatio="xMidYMid slice" 
        focusable="false">
        <!--title>Placeholder</title>
        <rect width="100%" height="100%" fill="#777"/>
        <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text-->
        <image title="<?= $component->image->title; ?>" href="<?= $component->image->url; ?>"/>
      </svg>

        <h2><?= $component->heading; ?></h2>
        <p><?= $component->text; ?></p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
