
<div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading"><?=$title; ?></h2>
        <p class="lead"><?=$description; ?></p>
      </div>
      <div class="col-md-5">
        
        
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto"  width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
        <image title="<?= $title; ?>" href="<?= $url; ?>"/>
       </svg>
        
      </div>
    </div>