<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<link href="/css/footer/v1/style.css" rel="stylesheet">
<script src="/js/footer/v1/plugin.js" type="javascript"></script>

    <p class="float-end">
        <a href="#">
            Back to top
        </a>
    </p>
    <p>
        &copy; 2017-2021 Rhodes, Inc. <a href="<?= $footer->copyright; ?>"><?= $footer->right_text; ?> </a>
    </p>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
